server:
  port: 9999

spring:
  datasource:
    username: root
    password: 030709
    url: jdbc:mysql:///mshd

  redis:
    port: 6379
    host: localhost


ftp:
  server:
    address: 10.129.15.13
    port: 21
    baseDir: /ftp
  user:
    name: 3142469253@qq.com
    password: 15932041h





logging:
  level:
    com.qinuan: debug

