server:
  port: 9999

spring:
  datasource:
    username: root
    password: 030709
    url: jdbc:mysql:///mshd

  redis:
    port: 6379
    host: localhost

ftp:
  server: localhost
  port: 21
  username: ftpuser
  password: ftppassword




logging:
  level:
    com.qinuan: debug

